[project]
name = "OpenMaverick"
version = "0.2.0"
description = "The OpenMaverick API for FlightGear"
readme = "README.md"

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
